[package]
name = "mvdb"
version = "0.1.0"
authors = ["James Munns <james.munns@gmail.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
error-chain = "0.10"

locked_accessors = {path="../locked_accessors"}